export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";
export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";

export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";
export const POST_REGISTER_LOADING = "POST_REGISTER_LOADING";

export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILED = "GET_SERVICES_FAILED";
export const GET_SERVICES_LOADING = "GET_SERVICES_LOADING";

export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS";
export const GET_BANNERS_FAILED = "GET_BANNERS_FAILED";
export const GET_BANNERS_LOADING = "GET_BANNERS_LOADING";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";

export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED";
export const GET_BALANCE_LOADING = "GET_BALANCE_LOADING";

export const GET_HISTORIES_SUCCESS = "GET_HISTORIES_SUCCESS";
export const GET_HISTORIES_FAILED = "GET_HISTORIES_FAILED";
export const GET_HISTORIES_LOADING = "GET_HISTORIES_LOADING";

export const CHANGE_TOPUP_VALUE = "CHANGE_TOPUP_VALUE";
export const POST_TOPUP_SUCCESS = "POST_TOPUP_SUCCESS";
export const POST_TOPUP_FAILED = "POST_TOPUP_FAILED";
export const POST_TOPUP_LOADING = "POST_TOPUP_LOADING";
